### ISSUE TITLE
Backend supports saving file to specific branch

### ISSUE THREAD

**Issue by guotin** [ohtuprojekti-eficode/WEVC#110]
* Change saving file in backend to push a branch with a branch name given as a parameter

OR

* Make a new function to handle branch saving/pushing and leave current function to handle master push

thoughts?

**Comment by ilkkamaksy** [comment]
I would suggest chopping saveChanges in git.ts service in smaller functions doing only one thing each, e.g. 

- gitCreateNewBranch: create a new branch: use param branch name if given, else use default
- gitCheckoutToBranch: make sure the branch is set to where user wants it; current/new branch 
- gitAddFiles: git add
- gitCommit: git commit;  use given commit message, if none given, use default (perhaps a good idea to isolate defining commit message to a separate function too)
- gitAddRemote
- gitPush
- etc

Then we can either use those functions directly in resolvers or treat them as "private" and create a few "public" functions which take care of the logic. Thoughts?

**Comment by ilkkamaksy** [comment]
note that issue #97 is also related
