### ISSUE TITLE
Graphql introduction session

### ISSUE THREAD

**Issue by ilkkamaksy** [ohtuprojekti-eficode/WEVC#43]
Those who have more experience with Graphql introduce others to it

**Comment by guotin** [comment]
Could we decide what to do with this? Anyone who wants this could suggest some times when to have a session like this. Also check out (if you haven't already) [FullstackOpen](https://fullstackopen.com/en/part8).

**Comment by guotin** [comment]
25.10. 10:00 - 11:30
