### ISSUE TITLE
Rename and improve github actions

### ISSUE THREAD

**Issue by guotin** [ohtuprojekti-eficode/WEVC#94]
#### Ideas for improvement

* Rename workflow files to be more descriptive
  * For example `WEVC CI/CD` to something like `MASTER PUSH` 
* Rename steps
  * `Build` could be something like `Compile typescript`
  * `Cypress test` could be something like `E2E testing`
* Combine some steps
  * Perhaps the unit testing steps could also do the required installs
* Make sure docker deployment is in the same step sequence with testing to prevent some random master pushing messing up production

**Comment by Tattoo** [comment]
My suggestion is try to make as simple pipeline as possible with as few steps as possible (of course, use common sense)
